//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumpList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JumpList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0006f647f9488d7a|AIM 7.5.11.9 (custom AppID + JL support)
        ///00098b0ef1c84088|fulDC 6.78
        ///012dc1ea8e34b5a6|Microsoft Paint 6.1
        ///01b29f0dc90366bb|AIM 5.9.3857
        ///03d877ec11607fe4|Thunderbird 6.0.2
        ///044a50e6c87bc012|Classic FTP Plus 2.15
        ///050620fe75ee0093|VMware Player 3.1.4
        ///05e01ecaf82f7d8e|Scour Exchange 0.0.0.228
        ///06059df4b02360af|Kadu 0.10.0 / 0.6.5.5
        ///070b52cf73249257|Sococo 1.5.0.2274
        ///0a1d19afe5a80f80|FileZilla 2.2.32
        ///0a79a7ce3c45d781|CuteFTP 7.1 (Build 06.06.2005.1)
        ///0b17d3d0c9ca7e29|Document ViewerPica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppIDs {
            get {
                return ResourceManager.GetString("AppIDs", resourceCulture);
            }
        }
    }
}
